# Generated by Django 4.0.5 on 2022-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(blank=True, help_text='最后登陆时间', max_length=50),
        ),
    ]
